// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozioblmgaqdawtyuujfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96aW9ibG1nYXFkYXd0eXV1amZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3Mzg5NjcsImV4cCI6MjA2MzMxNDk2N30.ud1Ow0swjiIyZd7NXclCdi9hiY5qCRcubhZHEv4mawM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);